name: CodeCov

on:
  push:
    branches: [Develop, master]
  pull_request:
    branches: [Develop, master]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.8
      uses: actions/setup-python@master
      with:
        python-version: 3.8

    - name: 'generate report'
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -e .[test]
        pip install coverage
        cd tests/
        coverage run -m unittest

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
        fail_ci_if_error: true
